[package]
name = "iphone_counter_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3"
zerofrom = "0.1.5"
litemap = "0.7.4"
tokio = { version = "1", features = ["full"] }
